#@ load("@ytt:data", "data")
#@ load("helpers.lib.yaml", "namespace", "labels", "secret_annotations")
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: #@ data.values.app.secret.name
  namespace: #@ namespace()
  labels: #@ labels("app")
stringData:
  ADMIN_JWT_SECRET: "8gr1zRio9aXPQwQEtZlOgQ=="
  DATABASE_PASSWORD: "78fwRgGBae"
